api_platform:
  exception_to_status:
    Symfony\Component\Serializer\Exception\ExceptionInterface: 400
    ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
    ApiPlatform\Core\Exception\FilterValidationException: 400
    Doctrine\ORM\OptimisticLockException: 409

    # Custom mapping
    App\Exception\ObjectNotFoundException: 404
    App\Exception\ApplicationIdNotFoundException: 401
    App\Exception\AppUnauthorizedHttpException: 401
    App\Exception\AppEntityValidationException: 400
    App\Exception\ValidatorParamNotFoundException: 404

  #formats:
  #jsonld:   ['application/ld+json']
  #jsonapi:  ['application/vnd.api+json']
  #json:     ['application/json']
  #yaml:     ['application/x-yaml']
  collection:
    pagination:
      enabled: true
      #partial: true
      #client_partial: true # Disabled by default
      #partial_parameter_name: 'partial' # Default value
      client_items_per_page: true # Disabled by default, allow the client obtain specific items total per page
      items_per_page: 30 # default items per page, can be changed besides param 'itemsPerPage', but exist maximum items per page (100)
      maximum_items_per_page: 100
      items_per_page_parameter_name: perPage # Default value
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/json'] #merge-patch+json
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
